name: Arch build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pkgbuild: [ PKGBUILD, git.PKGBUILD ]
    steps:
    - uses: actions/checkout@v1
    - run: make arch-docker-build
    - run: |
        BUILDDIR=$(mktemp -d build.XXXXXXXXXX)
        PKGDEST=$(mktemp -d pkg.XXXXXXXXXX)
        SRCDEST=$(mktemp -d src.XXXXXXXXXX)
    - run: |
        docker run \
          -v $(pwd):/home/arch \
          -v /tmp:/tmp \
          -e BUILDDIR="$BUILDDIR" \
          -e PKGDEST="$PKGDEST" \
          -e SRCDEST="$SRCDEST" \
          arch \
          bash -c 'env && make ARCH_PKGBUILD=${{ matrix.pkgbuild }} arch-install && which map-io'