name: Arch build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pkgbuild: [ PKGBUILD, git.PKGBUILD ]
    steps:
    - uses: actions/checkout@v1
    - run: make arch-docker-build
    - run: docker run -v $(pwd):/home/arch arch bash -c 'make ARCH_PKGBUILD=${{ matrix.pkgbuild }} arch-install && which map-io'