name: Arch build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pkgbuild: [ PKGBUILD, git.PKGBUILD ]
    steps:
    - uses: actions/checkout@v1
    - run: make arch-docker-build
    - run: |
        echo BUILDDIR=/tmp/$(mktemp -d build.XXXXXXXXXX) >> $GITHUB_ENV
        echo PKGDEST=/tmp/$(mktemp -d pkg.XXXXXXXXXX) >> $GITHUB_ENV
        echo SRCDEST=/tmp/$(mktemp -d src.XXXXXXXXXX) >> $GITHUB_ENV
    - run: |
        docker run \
          -v /tmp:/tmp \
          -v $(pwd):/home/arch/mount \
          -e BUILDDIR="$BUILDDIR" \
          -e PKGDEST="$PKGDEST" \
          -e SRCDEST="$SRCDEST" \
          arch \
          bash -c 'cd mount && make ARCH_PKGBUILD=${{ matrix.pkgbuild }} arch-install && which map-io'